version: '3'

networks:
  my_conection:
    driver: bridge

services:

  emqx:

    image: emqx/emqx:5.3

    container_name: emqx

    networks:
      - my_conection

    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx
      - EMQX_NODE__DIST_LISTEN_MIN=6369
      - EMQX_NODE__DIST_LISTEN_MAX=6379
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_auth_username

    ports:
      - 1883:1883 
      - 8883:8883
      - 8083:8083
      - 18083:18083 # porta da dashbaord web -> localhost:1808

  rabbitmq:

    image: rabbitmq:management

    container_name: rabbitmq

    networks:
      - my_conection

    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

    ports:
      - 15672:15672 # porta da dashbaord web -> localhost:15672
      - 5672:5672 # porta do broker
      - 15692:15692

  device_simulator:

    image: device_simulator

    container_name: device_simulator

    networks:
      - my_conection

    environment:
      - MQTT_HOST=emqx:1883
      - MQTT_PROTOCOL=tcp
      - MQTT_USER=admin
      - MQTT_PASSWORD=admin
      - TIME_TEMP=1000
      - TIME_HUMIDITY=1000 
      - LOG_LEVEL=debug

  # rmq-bridge:

  #   image: rmq-bridge

  #   container_name: rmq-bridge

  #   networks:
  #     - my_conection

  #   environment:
  #     - RUST_LOG=debug
  #     - MQTT_HOST=emqx:1883
  #     - MQTT_PROTOCOL=tcp
  #     - MQTT_PORT=1883
  #     - MQTT_CLIENT_ID=my-client-id@1234
  #     - MQTT_USER=admin
  #     - MQTT_PASSWORD=admin

  #     - RABBITMQ_HOST=rabbitmq:5672
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=guest
  #     - RABBITMQ_PASSWORD=guest
  #     - RABBITMQ_QUEUE=Dataset
  #     - RABBITMQ_EXCHANGE=Hedro_Test